entity: lavender
project: toy_structured_readmission
dataset_path: ../synthetic_data/raw/structured/toy_readmission_splits
keep_cols: ['length_of_stay','acute_visit', 'past_ed_visit', 'charles_comorbidity', 'readmission']
feats: ['length_of_stay','acute_visit', 'past_ed_visit', 'charles_comorbidity']
categorical_feats: []
labels: ['readmission']
objective: binary:logistic
